# Generated by Django 4.0.1 on 2022-01-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('Dala', 'Dala'), ('Nasarawa', 'Nasarawa'), ('Fagge', 'Fagge'), ('Bichi', 'Bichi'), ('Kano Municipal', 'Kano Municipal')], max_length=30)),
                ('city', models.CharField(choices=[('Kano', 'Kano')], max_length=40)),
            ],
        ),
    ]
