# Generated by Django 4.0.1 on 2022-02-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
