# Generated by Django 4.0.1 on 2022-02-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_detail_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='CustormerDetail',
        ),
    ]
