# Generated by Django 4.0.1 on 2022-02-07 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_detail_custormerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='custormerdetail',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custormerdetail',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
