# Generated by Django 4.0.1 on 2022-02-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_custormerdetail_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custormerdetail',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
