# Generated by Django 4.0.6 on 2022-11-11 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_custormerdetail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='custormerdetail',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
